### ISSUE TITLE
「周报」自荐

### ISSUE THREAD

**Issue by alaskasquirrel** [liugezhou/liugezhou.github.io#4]
https://github.com/alaskasquirrel/Email-newsletter-RSS 搜录中文newsletter
https://github.com/alaskasquirrel/Chinese-Podcasts 搜集中文播客
https://github.com/alaskasquirrel/Privacy 关注隐私
这些日常都是本人维护更新，寻求好奇者参与。

**Comment by liugezhou** [comment]
> https://github.com/alaskasquirrel/Email-newsletter-RSS 搜录中文newsletter 
 https://github.com/alaskasquirrel/Chinese-Podcasts 搜集中文播客 
 https://github.com/alaskasquirrel/Privacy 关注隐私 这些日常都是本人维护更新，寻求好奇者参与。

Got it。
